//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.17 at 04:13:52 PM PST
//

package org.geoserver.mapml.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for inputRelType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="inputRelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="map"/>
 *     &lt;enumeration value="tile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "inputRelType")
@XmlEnum
public enum InputRelType {
    @XmlEnumValue("map")
    IMAGE("image"),
    @XmlEnumValue("tile")
    TILE("tile"),
    @XmlEnumValue("pixel")
    PIXEL("pixel");
    private final String value;

    InputRelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InputRelType fromValue(String v) {
        for (InputRelType c : InputRelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
