pmtiles=PMTiles file URI

storage.provider=Storage provider
storage.backends=Storage backends
storage.provider.file=Local file
storage.provider.http=HTTP
storage.provider.s3=AWS S3
storage.provider.azure=Azure
storage.provider.azure-datalake=Azure Data Lake Storage Gen2
storage.provider.gcs=Google Cloud

storage.group.s3=AWS S3 parameters
storage.group.azure=Azure parameters
storage.group.gcs=Google Cloud parameters
storage.group.http=HTTP parameters
storage.group.caching=Caching parameters

storage.caching.enabled=Enable the storage memory cache

storage.s3.endpoint=Service endpoint
storage.s3.region=AWS region
storage.s3.anonymous=Anonymous (public bucket)
storage.s3.aws-access-key-id=AWS access key id
storage.s3.aws-secret-access-key=AWS secret access key
storage.s3.use-default-credentials-provider=Use the AWS default credentials provider
storage.s3.default-credentials-profile=AWS credentials profile
storage.s3.force-path-style=Force S3 path-style access
storage.s3.requester-pays=Requester pays

storage.azure.endpoint=Blob service endpoint
storage.azure.blob-name=Blob name
storage.azure.anonymous=Anonymous (public container)
storage.azure.account-key=Account key
storage.azure.sas-token=SAS token
storage.azure.connection-string=Connection string
storage.azure.max-retries=Max retries
storage.azure.retry-delay=Retry delay
storage.azure.max-retry-delay=Max retry delay
storage.azure.try-timeout=Per-try timeout

storage.gcs.endpoint=Custom GCS endpoint
storage.gcs.project-id=Project id
storage.gcs.quota-project-id=Quota project id
storage.gcs.default-credentials-chain=Use the application default credentials
storage.gcs.user-project=Billing project (requester pays)

storage.http.timeout-millis=Connection timeout (ms)
storage.http.trust-all-certificates=Trust all TLS certificates
storage.http.username=Basic auth username
storage.http.password=Basic auth password
storage.http.bearer-token=Bearer token
storage.http.api-key-headername=API key header name
storage.http.api-key=API key
storage.http.api-key-value-prefix=API key value prefix
