/* (c) 2014 Open Source Geospatial Foundation - all rights reserved
 * (c) 2001 - 2014 OpenPlans
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.wms;

import java.util.List;
import org.geoserver.platform.GeoServerExtensions;
import org.geoserver.platform.ServiceException;
import org.geotools.util.Version;
import org.geotools.xml.transform.TransformerBase;
import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

/**
 * WMS GetCapabilities operation default implementation.
 *
 * @author Gabriel Roldan
 */
public class GetCapabilities implements ApplicationContextAware {

    private final WMS wms;
    private List<GetCapabilitiesTransformerFactory> factories;

    public GetCapabilities(final WMS wms) {
        this.wms = wms;
    }

    /** @param request get capabilities request, as generated by */
    public TransformerBase run(final GetCapabilitiesRequest request) throws ServiceException {

        final Version version = WMS.version(request.getVersion(), WMS.VERSION_1_3_0);
        if (version == null) {
            throw new IllegalArgumentException("version not supplied.");
        }

        // UpdateSequence handling for WMS: see WMS 1.1.1 page 23
        long reqUS = -1;
        if (request.getUpdateSequence() != null
                && !"".equals(request.getUpdateSequence().trim())) {
            try {
                reqUS = Long.parseLong(request.getUpdateSequence());
            } catch (NumberFormatException nfe) {
                throw new ServiceException("GeoServer only accepts numbers in the updateSequence parameter");
            }
        }
        long geoUS = wms.getUpdateSequence();
        if (reqUS > geoUS) {
            throw new ServiceException(
                    "Client supplied an updateSequence that is greater than the current server updateSequence",
                    "InvalidUpdateSequence");
        }
        if (reqUS == geoUS) {
            throw new ServiceException(
                    "WMS capabilities document is current (updateSequence = " + geoUS + ")", "CurrentUpdateSequence");
        }
        // otherwise it's a normal response...
        for (GetCapabilitiesTransformerFactory factory : factories) {
            TransformerBase transformer = factory.createTransformer(request);
            if (transformer != null) {
                return transformer;
            }
        }

        throw new ServiceException("No GetCapabilities transformer found for version " + version);
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.factories = GeoServerExtensions.extensions(GetCapabilitiesTransformerFactory.class);
    }
}
