default.min=-25
default.max=25

direction.convention=FROM
direction.unit=DEG

band.speed.exact=speed,wind_speed,windspeed,ws
band.speed.contains=spd,wspd,wind_spd,wind_speed

band.dir.exact=direction,wind_direction,winddir,wd
band.dir.contains=dir,wdir,wind_dir,wind_direction

band.u.exact=u,uwnd,ugrd
band.u.contains=eastward_wind,u_component,_u_

band.v.exact=v,vwnd,vgrd
band.v.contains=northward_wind,v_component,_v_