pngwind.default.min=-25
pngwind.default.max=25

pngwind.direction.convention=FROM
pngwind.direction.unit=DEG

pngwind.band.speed.exact=speed,wind_speed,windspeed,ws
pngwind.band.speed.contains=spd,wspd,wind_spd,wind_speed

pngwind.band.dir.exact=direction,wind_direction,winddir,wd
pngwind.band.dir.contains=dir,wdir,wind_dir,wind_direction

pngwind.band.u.exact=u,uwnd,ugrd
pngwind.band.u.contains=eastward_wind,u_component,_u_

pngwind.band.v.exact=v,vwnd,vgrd
pngwind.band.v.contains=northward_wind,v_component,_v_