INSERT INTO collection
(id, name, "primary", "htmlDescription", footprint, "timeStart", "timeEnd", productcqlfilter, masked, "eoIdentifier", "eoProductType", "eoPlatform", "eoPlatformSerialIdentifier", "eoInstrument", "eoSensorType", "eoCompositeType", "eoProcessingLevel", "eoOrbitType", "eoSpectralRange", "eoWavelength", "eoSecurityConstraints", "eoDissemination", "eoAcquisitionStation")
VALUES(17, 'SENTINEL2', NULL, '<div id="sentinel2-description"><p><strong>Sentinel-2</strong> is an Earth observation mission developed by ESA as part of the Copernicus Programme to perform terrestrial observations in support of services such as forest monitoring, land cover changes detection, and natural disaster management.</p><p>It consists of two identical satellites, Sentinel-2A and Sentinel-2B.</p><p>The Sentinel-2 satellites will each carry a single multi-spectral instrument (MSI) with 13 spectral channels in the visible/near infrared (VNIR) and short wave infrared spectral range (SWIR).</p></div>', ST_GeomFromText('POLYGON((-179 89,179 89,179 -89,-179 -89,-179 89))', 4326), '2016-02-26 10:20:21.000', '2015-07-01 10:20:21.000', NULL, NULL, 'SENTINEL2', 'S2MSI1C', 'Sentinel-2', 'A', 'MSI', 'OPTICAL', NULL, 'Level-1C', 'LEO', NULL, NULL, NULL, NULL, NULL);
INSERT INTO collection
(id, name, "primary", "htmlDescription", footprint, "timeStart", "timeEnd", productcqlfilter, masked, "eoIdentifier", "eoProductType", "eoPlatform", "eoPlatformSerialIdentifier", "eoInstrument", "eoSensorType", "eoCompositeType", "eoProcessingLevel", "eoOrbitType", "eoSpectralRange", "eoWavelength", "eoSecurityConstraints", "eoDissemination", "eoAcquisitionStation")
VALUES(32, 'SENTINEL1', NULL, '<div id="sentinel1-description"><p><strong>Sentinel-1</strong> is a space mission funded by the European Union and carried out by the ESA within the Copernicus Programme, consisting of a constellation of two satellites.</p><p>The payload of Sentinel-1 is a Synthetic Aperture Radar in C band that provides continuous imagery (day, night and all weather).</p><p>Sentinel-1 spacecrafts are designed to carry following instruments:</p><ul><li>a single C band SAR with its electronics (SES);</li><li>a SDRAM-based mass memory (DSHA), with an active data storage capacity of about 1,44 Gbit (168 GiB)</li></ul></div>', ST_GeomFromText('POLYGON((-179 89,179 89,179 -89,-179 -89,-179 89))', 4326), '2015-02-26 10:20:21.000', '2014-05-01 10:20:21.000', NULL, NULL, 'SENTINEL1', NULL, 'Sentinel-1', NULL, 'SAR', 'RADAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO collection
(id, name, "primary", "htmlDescription", footprint, "timeStart", "timeEnd", productcqlfilter, masked, "eoIdentifier", "eoProductType", "eoPlatform", "eoPlatformSerialIdentifier", "eoInstrument", "eoSensorType", "eoCompositeType", "eoProcessingLevel", "eoOrbitType", "eoSpectralRange", "eoWavelength", "eoSecurityConstraints", "eoDissemination", "eoAcquisitionStation")
VALUES(31, 'LANDSAT8', NULL, '<div id="landsat8-description"><p><strong>Landsat 8</strong> is an American Earth observation satellite launched on February 11, 2013. It is the eighth satellite in the Landsat program; the seventh to reach orbit successfully.</p><p>Originally called the Landsat Data Continuity Mission (LDCM), it is a collaboration between NASA and the United States Geological Survey (USGS).</p><p>the Landsat 8''s Operational Land Imager (OLI) collects data from nine spectral bands. Seven of the nine bands are consistent with the Thematic Mapper (TM) and Enhanced Thematic Mapper Plus (ETM+) sensors found on earlier Landsat satellites, providing for compatibility with the historical Landsat data, while also improving measurement capabilities.</p></div>', ST_GeomFromText('POLYGON((-179 89,179 89,179 -89,-179 -89,-179 89))', 4326), '1988-02-26 10:20:21.000', '2013-03-01 10:20:21.000', NULL, NULL, 'LANDSAT8', NULL, '', NULL, 'OLI', 'OPTICAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
