/* (c) 2025 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.web.security.oauth2.intgration.keycloak;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.List;
import java.util.Map;
import org.geoserver.data.test.SystemTestData;
import org.geoserver.security.GeoServerSecurityFilterChain;
import org.geoserver.security.GeoServerSecurityManager;
import org.geoserver.security.RequestFilterChain;
import org.geoserver.security.config.SecurityManagerConfig;
import org.geoserver.security.oauth2.config.GeoServerOAuth2LoginFilterConfig;
import org.geoserver.security.oauth2.config.OpenIdRoleSource;
import org.geoserver.security.oauth2.login.GeoServerOAuth2LoginAuthenticationFilter;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;

/**
 * Basic login is as follows:
 *
 * <p>1. Get the GS homepage (via wicket) <br>
 * 2. There should be a button/anchor that sends the user to "/web/oauth2/authorization/openidconnect__oidc" <br>
 * 3. Click the button <br>
 * 4. Response should be a redirect to keycloak <br>
 * * verify the URL's params <br>
 * * remember the `nonce` and `state` params (these are pre-login generated by spring) <br>
 * 5. send the request to the keycloak container <br>
 * 6. Keycloak will respond with a login form <br>
 * * from the response, extract the form's {@code <form action=....> URL} <br>
 * * this will have a bunch of keycloak-specific parameters <br>
 * * capture the cookies keycloak sets <br>
 * 7. submit a POST request to keycloak <br>
 * * use the form's `action=....` (with a bunch of parms) as the URL <br>
 * * In the body, put `username=admin&password=admin&credentialId=` (for user admin, password admin) <br>
 * * set `Content-Type` to `application/x-www-form-urlencoded` <br>
 * * attach keycloak's cookies <br>
 * 8. The response will be a redirect to GeoServer (code request) <br>
 * * will be to `http://localhost:8080/geoserver/web/login/oauth2/code/oidc` <br>
 * * will have a bunch of params (including `code`) <br>
 * 9. Execute, in GS, the redirect URL <br>
 * 10. Extract the security context (from mock GS) <br>
 * 11. Validate the info in the security context <br>
 * NOTE: all GS requests should use the same session
 *
 * <p>This is executing a login in a manner VERY similar to how a user would on the browser. See
 * `executeOnSecurityFilters()` - this is how we emulate a non-wicket request.
 *
 * <p>Please see the README.md in the `resources/org/geoserver/web/security/oauth2/intgration/keycloak` directory for
 * more information on how to change the keycloak configuration.
 */
public class KeyCloakIntegrationTest extends KeyCloakIntegrationTestSupport {

    /**
     * Configure GS logging level.
     *
     * @return logging level
     */
    @Override
    protected String getLogConfiguration() {
        return "VERBOSE_LOGGING";
    }

    @BeforeClass
    public static void beforeClassLocal() {
        // for test cases this needs to be set by the OIDC module so it knows the mock server's base URL
        // Must match baseRedirectUri (without trailing slash) set in onSetUp() so that after
        // XStream deserialization, resolveBaseRedirectUri() returns the same base.
        System.setProperty("OPENID_TEST_GS_PROXY_BASE", "http://localhost:8080/geoserver");
    }

    /**
     * Login as admin/admin.
     *
     * @throws Exception error occurred
     */
    @Test
    public void test_login_as_admin() throws Exception {
        OAuth2AuthenticationToken auth = login("admin", "admin");

        // validate the security context (auth)
        assertTrue(auth.isAuthenticated());
        assertEquals("openidconnect__oidc", auth.getAuthorizedClientRegistrationId());

        assertEquals("admin@example.com", auth.getPrincipal().getName());
        assertEquals("admin@example.com", auth.getName());

        assertEquals(2, auth.getAuthorities().size());
        assertEquals(2, auth.getPrincipal().getAuthorities().size());
        assertTrue(auth.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .toList()
                .contains("ROLE_AUTHENTICATED"));
        assertTrue(auth.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .toList()
                .contains("ROLE_ADMINISTRATOR"));

        assertEquals("admin", auth.getPrincipal().getAttributes().get("preferred_username"));
        assertEquals("gs-client", auth.getPrincipal().getAttributes().get("azp"));
        assertEquals("admin", auth.getPrincipal().getAttributes().get("family_name"));
        assertEquals("admin admin", auth.getPrincipal().getAttributes().get("name"));

        // get IDTOKEN.resource_access.gs-client.roles
        // this should be "geoserverAdmin" (from keycloak)
        OidcUser principal = (OidcUser) auth.getPrincipal();
        @SuppressWarnings("rawtypes")
        Map resourceAccess = (Map) principal.getIdToken().getClaim("resource_access");
        assertNotNull(resourceAccess);
        @SuppressWarnings("rawtypes")
        Map gsClient = (Map) resourceAccess.get("gs-client");
        assertNotNull(gsClient);
        @SuppressWarnings("rawtypes")
        List gsClientRoles = (List) gsClient.get("roles");
        assertEquals("geoserverAdmin", gsClientRoles.get(0));
    }

    /**
     * Login as user_sample1/user_sample1.
     *
     * @throws Exception error occurred
     */
    @Test
    public void test_login_as_user_sample1() throws Exception {
        OAuth2AuthenticationToken auth = login("user_sample1", "user_sample1");

        // validate the security context (auth)
        assertTrue(auth.isAuthenticated());
        assertEquals("openidconnect__oidc", auth.getAuthorizedClientRegistrationId());

        assertEquals("user_sample1@example.com", auth.getPrincipal().getName());
        assertEquals("user_sample1@example.com", auth.getName());

        assertEquals(1, auth.getAuthorities().size());
        assertEquals(1, auth.getPrincipal().getAuthorities().size());
        assertTrue(auth.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .toList()
                .contains("ROLE_AUTHENTICATED"));

        assertEquals("user_sample1", auth.getPrincipal().getAttributes().get("preferred_username"));
        assertEquals("gs-client", auth.getPrincipal().getAttributes().get("azp"));
        assertEquals("sample1", auth.getPrincipal().getAttributes().get("family_name"));
    }

    /**
     * setup GS with an oidc filter that points to our testcontainer's keycloak.
     *
     * @param testData GS config
     * @throws Exception error occurred
     */
    @Override
    protected void onSetUp(SystemTestData testData) throws Exception {
        super.onSetUp(testData);

        String baseKeycloakUrl = keycloakContainer.getAuthServerUrl() + "/realms/gs-realm/protocol/openid-connect";
        // setup openid
        GeoServerSecurityManager manager = getSecurityManager();
        GeoServerOAuth2LoginFilterConfig filterConfig = new GeoServerOAuth2LoginFilterConfig();
        filterConfig.setName("openidconnect");
        filterConfig.setClassName(GeoServerOAuth2LoginAuthenticationFilter.class.getName());
        filterConfig.setOidcEnabled(true);
        filterConfig.setOidcClientId(oidcClient);
        filterConfig.setOidcClientSecret(oidcClientSecret);
        filterConfig.setBaseRedirectUri("http://localhost:8080/geoserver/");
        filterConfig.calculateRedirectUris();
        filterConfig.setOidcTokenUri(baseKeycloakUrl + "/token");
        filterConfig.setOidcAuthorizationUri(baseKeycloakUrl + "/authorize");
        filterConfig.setOidcUserInfoUri(baseKeycloakUrl + "/userinfo");
        filterConfig.setOidcLogoutUri(baseKeycloakUrl + "/endSession");
        filterConfig.setOidcJwkSetUri(baseKeycloakUrl + "/certs");
        filterConfig.setOidcScopes("openid profile email phone address");
        filterConfig.setEnableRedirectAuthenticationEntryPoint(false);
        filterConfig.setOidcUserNameAttribute("email");
        filterConfig.setRoleSource(OpenIdRoleSource.IdToken);
        filterConfig.setTokenRolesClaim("roles");

        // setup roles extraction
        filterConfig.setRoleSource(OpenIdRoleSource.IdToken);
        filterConfig.setRoleConverterString("geoserverAdmin=ROLE_ADMINISTRATOR");
        filterConfig.setOnlyExternalListedRoles(true);
        filterConfig.setTokenRolesClaim("resource_access.gs-client.roles");

        filterConfig.setOidcForceAuthorizationUriHttps(false);
        filterConfig.setOidcForceTokenUriHttps(false);
        // filterConfig.setOidcJwsAlgorithmName(JwsAlgorithms.HS256);
        manager.saveFilter(filterConfig);

        // add our oidc to the WEB chain
        SecurityManagerConfig config = manager.getSecurityConfig();
        GeoServerSecurityFilterChain chain = config.getFilterChain();
        RequestFilterChain www = chain.getRequestChainByName("web");
        www.setFilterNames("openidconnect", "anonymous");

        manager.saveSecurityConfig(config);
    }
}
