//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.17 at 04:13:52 PM PST
//

package org.geoserver.mapml.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="tref" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="rel" use="required" type="{}relType" /&gt;
 *       &lt;attribute name="projection" type="{}projType" /&gt;
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="type" type="{}mimeType" /&gt;
 *       &lt;attribute name="hreflang" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "link", namespace = "http://www.w3.org/1999/xhtml/")
public class Link {

    @XmlAttribute(name = "href")
    @XmlSchemaType(name = "anyURI")
    protected String href;

    @XmlAttribute(name = "tref")
    @XmlSchemaType(name = "anySimpleType")
    protected String tref;

    @XmlAttribute(name = "rel", required = true)
    protected RelType rel;

    @XmlAttribute(name = "projection")
    protected ProjType projection;

    @XmlAttribute(name = "title")
    @XmlSchemaType(name = "anySimpleType")
    protected String title;

    @XmlAttribute(name = "type")
    protected MimeType type;

    @XmlAttribute(name = "hreflang")
    @XmlSchemaType(name = "anySimpleType")
    protected String hreflang;

    /**
     * Gets the value of the href property.
     *
     * @return possible object is {@link String }
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value allowed object is {@link String }
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the tref property.
     *
     * @return possible object is {@link String }
     */
    public String getTref() {
        return tref;
    }

    /**
     * Sets the value of the tref property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTref(String value) {
        this.tref = value;
    }

    /**
     * Gets the value of the rel property.
     *
     * @return possible object is {@link RelType }
     */
    public RelType getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     *
     * @param value allowed object is {@link RelType }
     */
    public void setRel(RelType value) {
        this.rel = value;
    }

    /**
     * Gets the value of the projection property.
     *
     * @return possible object is {@link ProjType }
     */
    public ProjType getProjection() {
        return projection;
    }

    /**
     * Sets the value of the projection property.
     *
     * @param value allowed object is {@link ProjType }
     */
    public void setProjection(ProjType value) {
        this.projection = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link MimeType }
     */
    public MimeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link MimeType }
     */
    public void setType(MimeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the hreflang property.
     *
     * @return possible object is {@link String }
     */
    public String getHreflang() {
        return hreflang;
    }

    /**
     * Sets the value of the hreflang property.
     *
     * @param value allowed object is {@link String }
     */
    public void setHreflang(String value) {
        this.hreflang = value;
    }
}
