//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.17 at 04:13:52 PM PST
//

package org.geoserver.mapml.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for relType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="relType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="stylesheet"/&gt;
 *     &lt;enumeration value="license"/&gt;
 *     &lt;enumeration value="alternate"/&gt;
 *     &lt;enumeration value="style"/&gt;
 *     &lt;enumeration value="self"/&gt;
 *     &lt;enumeration value="self style"/&gt;
 *     &lt;enumeration value="style self"/&gt;
 *     &lt;enumeration value="legend"/&gt;
 *     &lt;enumeration value="next"/&gt;
 *     &lt;enumeration value="zoomin"/&gt;
 *     &lt;enumeration value="zoomout"/&gt;
 *     &lt;enumeration value="image"/&gt;
 *     &lt;enumeration value="tile"/&gt;
 *     &lt;enumeration value="query"/&gt;
 *     &lt;enumeration value="features"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "relType")
@XmlEnum
public enum RelType {
    @XmlEnumValue("stylesheet")
    STYLESHEET("stylesheet"),
    @XmlEnumValue("license")
    LICENSE("license"),
    @XmlEnumValue("alternate")
    ALTERNATE("alternate"),
    @XmlEnumValue("style")
    STYLE("style"),
    @XmlEnumValue("self")
    SELF("self"),
    @XmlEnumValue("self style")
    SELF_STYLE("self style"),
    @XmlEnumValue("style self")
    STYLE_SELF("style self"),
    @XmlEnumValue("legend")
    LEGEND("legend"),
    @XmlEnumValue("next")
    NEXT("next"),
    @XmlEnumValue("zoomin")
    ZOOMIN("zoomin"),
    @XmlEnumValue("zoomout")
    ZOOMOUT("zoomout"),
    @XmlEnumValue("image")
    IMAGE("image"),
    @XmlEnumValue("tile")
    TILE("tile"),
    @XmlEnumValue("query")
    QUERY("query"),
    @XmlEnumValue("features")
    FEATURES("features");
    private final String value;

    RelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RelType fromValue(String v) {
        for (RelType c : RelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
