ALTER TABLE OBJECT_PROPERTY DISABLE CONSTRAINT FK_OBJECT_PROPERTY;
ALTER TABLE PROPERTY_TYPE DISABLE CONSTRAINT FK_TYPE_PROPERTY_TYPE;
ALTER TABLE OBJECT DISABLE CONSTRAINT FK_OBJECT_TYPE;
ALTER TABLE PROPERTY_TYPE DISABLE CONSTRAINT FK_PROPERTY_TYPE_TARGET_PROP;
ALTER TABLE OBJECT_PROPERTY DISABLE CONSTRAINT FK_OBJECT_PROPERTY_PROP_TYPE;

TRUNCATE TABLE OBJECT_PROPERTY;
TRUNCATE TABLE DEFAULT_OBJECT;
TRUNCATE TABLE PROPERTY_TYPE;
TRUNCATE TABLE TYPE;
TRUNCATE TABLE OBJECT;

ALTER TABLE OBJECT_PROPERTY ENABLE CONSTRAINT FK_OBJECT_PROPERTY;
ALTER TABLE PROPERTY_TYPE ENABLE CONSTRAINT FK_TYPE_PROPERTY_TYPE;
ALTER TABLE OBJECT ENABLE CONSTRAINT FK_OBJECT_TYPE;
ALTER TABLE PROPERTY_TYPE ENABLE CONSTRAINT FK_PROPERTY_TYPE_TARGET_PROP;
ALTER TABLE OBJECT_PROPERTY ENABLE CONSTRAINT FK_OBJECT_PROPERTY_PROP_TYPE;