#
# Contribute the MapLibre Tiles format to the configuration UI.
# See org.geoserver.gwc.GWC.getAdvertisedCachedFormats(PublishedType) javadocs
# for more info.
formats.vector = application/vnd.maplibre-vector-tile
formats.layergroup = application/vnd.maplibre-vector-tile
