/* (c) 2017 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.0-hudson-3037-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.07.27 at 11:06:51 PM CDT
//
package org.geoserver.wps.ppio.gpx;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Information about the GPX file, author, and copyright restrictions goes in the metadata section.
 * Providing rich, meaningful information about your GPX files allows others to search for and use
 * your GPS data.
 *
 * <p>Java class for metadataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="metadataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="author" type="{http://www.topografix.com/GPX/1/1}personType" minOccurs="0"/>
 *         &lt;element name="copyright" type="{http://www.topografix.com/GPX/1/1}copyrightType" minOccurs="0"/>
 *         &lt;element name="link" type="{http://www.topografix.com/GPX/1/1}linkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bounds" type="{http://www.topografix.com/GPX/1/1}boundsType" minOccurs="0"/>
 *         &lt;element name="extensions" type="{http://www.topografix.com/GPX/1/1}extensionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public class MetadataType {
    protected String name;

    protected String desc;

    protected PersonType author;

    protected CopyrightType copyright;

    protected List<LinkType> link;

    protected Calendar time;

    protected String keywords;

    protected BoundsType bounds;

    protected ExtensionsType extensions;

    /** Gets the value of the name property. */
    public String getName() {
        return name;
    }

    /** Sets the value of the name property. */
    public void setName(String value) {
        this.name = value;
    }

    /** Gets the value of the desc property. */
    public String getDesc() {
        return desc;
    }

    /** Sets the value of the desc property. */
    public void setDesc(String value) {
        this.desc = value;
    }

    /** Gets the value of the author property. */
    public PersonType getAuthor() {
        return author;
    }

    /** Sets the value of the author property. */
    public void setAuthor(PersonType value) {
        this.author = value;
    }

    /** Gets the value of the copyright property. */
    public CopyrightType getCopyright() {
        return copyright;
    }

    /** Sets the value of the copyright property. */
    public void setCopyright(CopyrightType value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the link property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the link property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     * getLink().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link LinkType }
     */
    public List<LinkType> getLink() {
        if (link == null) {
            link = new ArrayList<LinkType>();
        }

        return this.link;
    }

    /** Gets the value of the time property. */
    public Calendar getTime() {
        return time;
    }

    /** Sets the value of the time property. */
    public void setTime(Calendar value) {
        this.time = value;
    }

    /** Gets the value of the keywords property. */
    public String getKeywords() {
        return keywords;
    }

    /** Sets the value of the keywords property. */
    public void setKeywords(String value) {
        this.keywords = value;
    }

    /** Gets the value of the bounds property. */
    public BoundsType getBounds() {
        return bounds;
    }

    /** Sets the value of the bounds property. */
    public void setBounds(BoundsType value) {
        this.bounds = value;
    }

    /** Gets the value of the extensions property. */
    public ExtensionsType getExtensions() {
        return extensions;
    }

    /** Sets the value of the extensions property. */
    public void setExtensions(ExtensionsType value) {
        this.extensions = value;
    }
}
