ALTER TABLE OBJECT_PROPERTY DROP CONSTRAINT FK_OBJECT_PROPERTY;
ALTER TABLE PROPERTY_TYPE DROP CONSTRAINT FK_TYPE_PROPERTY_TYPE;
ALTER TABLE OBJECT DROP CONSTRAINT FK_OBJECT_TYPE;
ALTER TABLE PROPERTY_TYPE DROP CONSTRAINT FK_PROPERTY_TYPE_TARGET_PROPERTY;
ALTER TABLE OBJECT_PROPERTY DROP CONSTRAINT FK_OBJECT_PROPERTY_PROPERTY_TYPE;
DROP TABLE OBJECT CASCADE;
DROP TABLE OBJECT_PROPERTY CASCADE;
DROP TABLE TYPE CASCADE;
DROP TABLE PROPERTY_TYPE CASCADE;
DROP TABLE DEFAULT_OBJECT CASCADE;

