DROP SEQUENCE seq_OBJECT;
DROP SEQUENCE seq_TYPE;
DROP SEQUENCE seq_PROPERTY_TYPE;
DROP TABLE OBJECT CASCADE CONSTRAINTS;
DROP TABLE OBJECT_PROPERTY CASCADE CONSTRAINTS;
DROP TABLE TYPE CASCADE CONSTRAINTS;
DROP TABLE PROPERTY_TYPE CASCADE CONSTRAINTS;
DROP TABLE DEFAULT_OBJECT CASCADE CONSTRAINTS;
