curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @burg.sld "http://localhost:8080/geoserver/rest/styles?name=burg"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @giant_polygon.sld "http://localhost:8080/geoserver/rest/styles?name=giant_polygon"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @capitals.sld "http://localhost:8080/geoserver/rest/styles?name=capitals"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @simple_streams.sld "http://localhost:8080/geoserver/rest/styles?name=simple_streams"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @pophatch.sld "http://localhost:8080/geoserver/rest/styles?name=pophatch"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @restricted.sld "http://localhost:8080/geoserver/rest/styles?name=restricted"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @tiger_roads.sld "http://localhost:8080/geoserver/rest/styles?name=tiger_roads"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @poly_landmarks.sld "http://localhost:8080/geoserver/rest/styles?name=poly_landmarks"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @green.sld "http://localhost:8080/geoserver/rest/styles?name=green"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @rain.sld "http://localhost:8080/geoserver/rest/styles?name=rain"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @simpleRoads.sld "http://localhost:8080/geoserver/rest/styles?name=simple_roads"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @dem.sld "http://localhost:8080/geoserver/rest/styles?name=dem"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @popshade.sld "http://localhost:8080/geoserver/rest/styles?name=population"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @grass_poly.sld "http://localhost:8080/geoserver/rest/styles?name=grass"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @poi.sld "http://localhost:8080/geoserver/rest/styles?name=poi"
curl -u admin:geoserver -XPOST -H 'Content-type: application/sld+xml' -d @Lakes.sld "http://localhost:8080/geoserver/rest/styles?name=cite_lakes"


