/* (c) 2014 - 2016 Open Source Geospatial Foundation - all rights reserved
 * (c) 2001 - 2013 OpenPlans
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.web.wicket;

import static org.geoserver.web.util.WebUtils.IsWicketCssFileEmpty;

import org.apache.wicket.ajax.AjaxRequestTarget;
import org.apache.wicket.ajax.attributes.AjaxRequestAttributes;
import org.apache.wicket.ajax.attributes.IAjaxCallListener;
import org.apache.wicket.ajax.markup.html.AjaxLink;
import org.apache.wicket.markup.html.WebComponent;
import org.apache.wicket.markup.html.basic.Label;
import org.apache.wicket.markup.html.panel.Panel;
import org.apache.wicket.request.resource.ResourceReference;
import org.geoserver.web.CatalogIconFactory;

/**
 * A panel which encapsulates a link containing a image and an optional label.
 *
 * @author Justin Deoliveira, OpenGeo
 */
@SuppressWarnings("serial")
public abstract class ImageAjaxLink<T> extends Panel {

    private static final boolean isCssEmpty = IsWicketCssFileEmpty(ImageAjaxLink.class);

    @Override
    public void renderHead(org.apache.wicket.markup.head.IHeaderResponse response) {
        super.renderHead(response);
        // if the panel-specific CSS file contains actual css then have the browser load the css
        if (!isCssEmpty) {
            response.render(org.apache.wicket.markup.head.CssHeaderItem.forReference(
                    new org.apache.wicket.request.resource.PackageResourceReference(
                            getClass(), getClass().getSimpleName() + ".css")));
        }
    }

    protected WebComponent image;
    protected AjaxLink<T> link;

    /** Constructs the panel with a link containing an image. */
    public ImageAjaxLink(String id, ResourceReference imageRef) {
        this(id, imageRef, "");
    }

    /** Constructs the panel with a link containing an image and a label. */
    public ImageAjaxLink(String id, ResourceReference imageRef, String label) {
        super(id);
        link = new AjaxLink<>("link") {
            @Override
            public void onClick(AjaxRequestTarget target) {
                ImageAjaxLink.this.onClick(target);
            }

            @Override
            protected void updateAjaxAttributes(AjaxRequestAttributes attributes) {
                super.updateAjaxAttributes(attributes);
                attributes.getAjaxCallListeners().add(ImageAjaxLink.this.getAjaxCallListener());
            }
        };
        add(link);
        image = CatalogIconFactory.get().getIcon("image", imageRef);
        link.add(image);
        link.add(new Label("label", label));
    }

    protected IAjaxCallListener getAjaxCallListener() {
        return null;
    }

    /** Returns the image contained in this link (allows playing with its attributes) */
    public WebComponent getImage() {
        return image;
    }

    /**
     * Returns the link wrapped by the {@link ImageAjaxLink} panel (allows playing with its attributes and
     * enable/disable the link)
     */
    public AjaxLink<T> getLink() {
        return link;
    }

    /** Handles the onClick() event generated by clicking the link. */
    protected abstract void onClick(AjaxRequestTarget target);
}
